- id: '1613992817395'
  alias: Living room on switch
  description: ''
  trigger:
  - device_id: 5fa950b106851295d4b0df130fe228f0
    domain: hue
    platform: device
    type: remote_button_short_release
    subtype: turn_on
  condition: []
  action:
  - service: ifttt.trigger
    data:
      event: wiz_plug_on
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.candle_mode
  mode: single
- id: '1613992870546'
  alias: Living room off switch
  description: ''
  trigger:
  - device_id: 5fa950b106851295d4b0df130fe228f0
    domain: hue
    platform: device
    type: remote_button_short_release
    subtype: turn_off
  condition: []
  action:
  - service: ifttt.trigger
    data:
      event: wiz_plug_off
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.candle_mode
  mode: single
- id: '1614000704351'
  alias: Comfy time
  trigger:
  - platform: state
    entity_id: input_boolean.candle_mode
    to: 'on'
  action:
  - alias: Repeat this until the boolean is turned off
    repeat:
      sequence:
      - service: light.turn_on
        data_template:
          entity_id: light.hue_go_1
          brightness: '{{ (range(1, 25)|random) }}'
          color_temp: '{{ (range(400, 500)|random) }}'
          transition: 1
      - delay:
          milliseconds: '{{ (range(200, 700)|random) }}'
      - service: light.turn_on
        data_template:
          entity_id: light.hue_go_2
          brightness: '{{ (range(1, 25)|random) }}'
          color_temp: '{{ (range(400, 500)|random) }}'
          transition: 1
      - delay:
          milliseconds: '{{ (range(200, 700)|random) }}'
      until:
      - condition: state
        entity_id: input_boolean.candle_mode
        state: 'off'
  initial_state: true
  mode: single
- id: '1614003561194'
  alias: Comfy time on
  description: ''
  trigger:
  - device_id: 5fa950b106851295d4b0df130fe228f0
    domain: hue
    platform: device
    type: remote_button_long_release
    subtype: dim_up
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.candle_mode
  - service: media_player.select_source
    data:
      source: Netflix
    entity_id: media_player.lg_webos_smart_tv
  - type: turn_off
    device_id: 13851e7596cb27ba1b7052427665a612
    entity_id: light.living_spot_1
    domain: light
  - type: turn_off
    device_id: d3a64708d949b0299c6885d010fc47a6
    entity_id: light.living_spot_2
    domain: light
  - type: turn_off
    device_id: 57e20aeeae078b6005d9236b29401ac0
    entity_id: light.living_spot_3
    domain: light
  - type: turn_off
    device_id: 7124569a2e96c3e2b39b4c639a67dd55
    entity_id: light.living_spot_4
    domain: light
  - service: tts.amazon_polly_say
    data:
      entity_id: media_player.living_room_speaker
      message: Sit down and relax
    entity_id: media_player.living_room_speaker
  mode: single
- id: '1614638110403'
  alias: VPN Selection
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.vpn_location
  action:
  - service: script.vpn
    data:
      location: '{{ states(''input_select.vpn_location'') }}'
  mode: single
